# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: python

cache:
    directories:
      - ${TRAVIS_BUILD_DIR}/installers

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: "3.6"
      after_success:
        - codecov
    - os: linux
      dist: trusty
      sudo: required
      python: "3.5"
    - os: osx
      osx_image: xcode9.3
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.6
    - os: osx
      osx_image: xcode9.3
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.5

before_install:
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-khiva.sh
install:
  - source .CI/travis/install.sh
script:
  - source .CI/travis/build_and_test.sh
