# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: python
sudo: required
python:
  - "3.6"
services:
  - docker

before_install:
  - docker pull shapelets/khiva
  - docker run -i -t -d --name CI shapelets/khiva
  - docker cp . CI:/root
  - docker exec -it CI /bin/bash

install:
  - docker exec -it CI /bin/bash -c "pip3 install -r requirements.txt"
  - docker exec -it CI /bin/bash -c "pip3 install -r test-requirements.txt"
  - docker exec -it CI /bin/bash -c "python3 setup.py install"

script:
  - docker exec -it CI /bin/bash -c "python3 -m unittest discover tests/unit_tests *_tests.py -f"