# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: python

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: "3.6"
      env:
        - INSTALL_KHIVA_METHOD=github
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
      after_success:
        - codecov -F Linux -X gcov
    - os: linux
      dist: trusty
      sudo: required
      python: "3.5"
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
    - os: osx
      osx_image: xcode9.3
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.6.5
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - $HOME/.pyenv
          - $HOME/Library/Caches/Homebrew
      after_success:
        - codecov -F MacOS -X gcov
    - os: osx
      osx_image: xcode9.3
      language: generic
      env:
        - TRAVIS_PYTHON_VERSION=3.5.5
      cache:
        directories:
          - ${TRAVIS_BUILD_DIR}/installers
          - $HOME/.pyenv
          - $HOME/Library/Caches/Homebrew

before_install:
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-khiva.sh
install:
  - source .CI/travis/install.sh
script:
  - source .CI/travis/build_and_test.sh
