# Copyright (c) 2018 Shapelets.io
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

language: python
sudo: required
dist: trusty
python:
  - "3.5"
  - "3.6"

cache:
    directories:
      - ${HOME}/installers

before_install:
  - source .CI/travis/install-arrayfire.sh
  - source .CI/travis/install-khiva.sh
install:
  - source .CI/travis/install.sh
script:
  - source .CI/travis/build.sh
  - coverage run -m unittest discover tests/unit_tests *_tests.py -f -v
after_success:
  - codecov